version: 2.1

workflows:
  build-test-analyze:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm run test
  analyze:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit